name: FrizzlenEssentials
version: '1.0-SNAPSHOT'
main: org.frizzlenpop.frizzlenEssentials.FrizzlenEssentials
api-version: '1.21'
load: STARTUP
authors: [ frizzlenpop ]
description: A Plugin for Server Essentials
